version: '3.3'

services:

    kavita:
        image: kizaing/kavita:latest
        container_name: kavita
        privileged: true
        volumes:
            - ./manga:/manga:rw
            - ./comics:/comics:rw
            - ./epub:/epub:rw
            - ./data:/kavita/config:rw
        environment:
            - TZ=Europe/Madrid            
        ports:
            - "8200:5000"
        restart: unless-stopped

        
